# Uruchomienie z profilem: -Dspring.profiles.active=prod
# Domyślnie aktywny profil dev (lokalny development)
spring:
    profiles:
        active: dev
    application:
        name: GameHive
    threads:
        virtual:
            enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    config:
        import: optional:file:./secret.properties

jwt:
    activation:
        validityInSeconds: 86400
    refresh:
        validityInSeconds: 604800
        maxActiveTokensPerUser: 5
    access:
        validityInSeconds: 900
    passwordreset:
        validityInSeconds: 900